version: "3.2"
services:
  api:
    container_name: "poc-va-api"
    build: .
#    image: docker.pkg.github.com/thoughtworks-dps/poc-va-api/poc-va-api:latest
    ports:
      - "5000:5000"
  integration-test:
    container_name: "integration-test"
    image: "python:3.8.6-slim"
    depends_on:
      - api
    network_mode: host
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "pip3 install -r requirements.txt && pytest test/integration"
  swagger-test:
    container_name: "swagger-test"
    image: "apiaryio/dredd:12.2.0"
    depends_on:
      - api
    network_mode: host
    command: >
      sh -c "dredd http://localhost:5000/apispec_1.json http://127.0.0.1:5000 --language=python"