version: "3.8"
services:
  poc-va-api:
    build: .
    ports:
      - "5000:5000"
    networks:
      - poc
  integration-test:
    image: "python:3.8.6-slim"
    networks:
      - poc
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "pip3 install -r requirements.txt && pytest"
networks:
  poc:



