version: "3.4"
services:
  api:
    container_name: "poc-va-api"
    build: .
    ports:
      - "5000:5000"
  integration-test:
    container_name: "integration-test"
    image: "python:3.8.6-slim"
    depends_on:
      - api
    network_mode: host
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "pip3 install -r requirements.txt && pytest test/integration"