version: "3.8"
services:
  poc-va-api:
    build: .
    ports:
      - "5000:5000"
  integration-test:
    image: "python:3.8.6-slim"
    depends_on:
      - poc-va-api
    network_mode: host
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "pip3 install -r requirements.txt && pytest"