version: "3.2"
services:
  integration-test:
    container_name: "integration-test"
    image: "python:3.7-slim"
    network_mode: host
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "pip3 install -r requirements.txt && pytest test/integration"