version: 2.1
jobs:
  unit-test:
    docker:
      - image: cimg/python:3.8.6
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest test/unit

  integration-test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: |
          docker-compose up --exit-code-from integration-test

workflows:
  version: 2
  main:
    jobs:
      - unit-test
      - integration-test