version: 2
jobs:
  unit-test:
    docker:
      - image: cimg/python:3.8.6
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest test/unit

  integration-test:
    machine: true
    steps:
      - checkout
      - run: docker-compose -v
      - run: docker-compose up --exit-code-from integration-test

  push-image:
    machine: true
    steps:
      - checkout
      - run: docker ps

workflows:
  version: 2
  main:
    jobs:
      - unit-test
      - integration-test
      - push-image:
          requires:
            - unit-test
            - integration-test