version: 2.1
jobs:
  unit-test:
    docker:
      - image: cimg/python:3.8.6
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest test/unit

  integration-test:
    docker:
      - image: cimg/python:3.8.6
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: |
          docker create -v /app --name app alpine:3.4 /bin/true
          docker cp . app:/app
          docker-compose up -v app --exit-code-from integration-test

workflows:
  version: 2
  main:
    jobs:
      - unit-test
      - integration-test