version: 2.1

orbs:
  secrethub: secrethub/cli@1.0.0

jobs:
  unit-test:
    docker:
      - image: cimg/python:3.8.6
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest test/unit

  integration-test:
    machine:
      image: ubuntu-2004:202010-01
    environment:
      GITHUB_TOKEN: secrethub://vapoc/platform/svc/github/access-token
    steps:
      - checkout
      - secrethub/exec:
          step-name: publish
          command: |
            docker-compose up --exit-code-from integration-test

            echo "Circle tag: $CIRCLE_TAG"
            echo $GITHUB_TOKEN | docker login https://docker.pkg.github.com -u $GITHUB_USERNAME --password-stdin
            docker tag project_api:latest docker.pkg.github.com/thoughtworks-dps/poc-va-api/poc-va-api:0.0.1
            docker push docker.pkg.github.com/thoughtworks-dps/poc-va-api/poc-va-api:0.0.1

workflows:
  version: 2
  main:
    jobs:
      - unit-test
      - integration-test:
          context: dps-va-di