version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: cimg/python:3.8.6
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest test/unit