version: 2.1
orbs:
  secrethub: secrethub/cli@1.0.0
jobs:
  check-for-secrets:
    docker:
      - image: cimg/python:3.8.6
    steps:
      - checkout
      - run: |
          curl -sL https://raw.githubusercontent.com/awslabs/git-secrets/master/git-secrets >> git-secrets
          chmod +x git-secrets
          ./git-secrets --add-provider -- cat secrets-pattern.txt
          ./git-secrets --add --allowed 'secrets-pattern.txt:.*'
          ./git-secrets --scan
  unit-test:
    docker:
      - image: cimg/python:3.8.6
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest test/unit
  integration-test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: |
          mkdir -p workspace/images
          docker-compose up --exit-code-from integration-test
          docker save -o workspace/images/project_api_latest.tar project_api:latest
      - persist_to_workspace:
            root: workspace
            paths:
                - images/*
  tag:
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "c9:bc:64:42:70:68:38:b0:04:75:d1:15:b2:01:be:2f"
      - run: |
          current_version=$(git describe --abbrev=0 | tr -d 'v')
          new_version=$(docker run --rm alpine/semver semver -c -i patch $current_version)
          git config --global user.email "twdsp.io@thoughtworks.com"
          git config --global user.name "twdps.io"
          git tag -a "v${new_version}" -m "v${new_version}"
          git push origin master "v${new_version}"
  publish:
    machine: true
    environment:
      GITHUB_TOKEN: secrethub://vapoc/platform/svc/github/access-token
    steps:
      - checkout
      - attach_workspace:
            at: workspace/images
      - secrethub/exec:
          step-name: publish
          command: |
            echo "Circle Tag: ${CIRCLE_TAG}"
            docker load -i /tmp/workspace/images/project_api_latest.tar
            current_version=$(git describe --abbrev=0 | tr -d 'v')
            echo $GITHUB_TOKEN | docker login https://docker.pkg.github.com -u $GITHUB_USERNAME --password-stdin
            docker tag project_api:latest docker.pkg.github.com/thoughtworks-dps/poc-va-api/poc-va-api:$current_version
            docker push docker.pkg.github.com/thoughtworks-dps/poc-va-api/poc-va-api:$current_version
workflows:
  version: 2
  main:
    jobs:
      - check-for-secrets
      - unit-test
      - integration-test
      - tag:
          requires:
            - check-for-secrets
            - unit-test
            - integration-test
      - publish:
          context: dps-va-di
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/