version: 2.1
orbs:
  secrethub: secrethub/cli@1.0.0
executors:
  base-agent:
    docker:
      - image: twdps/di-circleci-infra-image:stable
jobs:
  persist_something:
    executor: base-agent
    steps:
      - checkout
      - run: |
          echo "test me" > test.txt
      - persist_to_workspace:
          root: /tmp
          paths: foobar/test.txt

  get_something_back:
    executor: base-agent
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/foobar
      - run: |
          cat /tmp/foobar/test.txt

workflows:
  version: 2
  main:
    jobs:
      - persist_something
      - get_something_back:
          requires:
            - persist_something